### ISSUE TITLE
Images Down

### ISSUE THREAD

**Issue by FredDoesStuff** [Mayuwhim/mystery-hat-bot#1]
Looks like the images were from discord, and I guess were from a now deleted message. Can't see any of the images anymore, so would appreciate if they were put back up.
Also, does this even work nowadays and with multiple cards (i have extra bingo sheet so i have 3)

**Comment by Mayuwhim** [comment]
The images weren't deleted but it seems the links did break, so I updated the links. Also updated readme for other issues. I quit dabs so I probably won't be maintaining the bot anymore.
